### ISSUE TITLE
Update the OOT documentation/tutorial adding the new yml tags to describe grc blocks

### ISSUE THREAD

**Issue by OtavioLara** [gnuradio/gnuradio#2684]
I am not finding in the gnuradio tutorials or even on the internet any kind of explanation about the new tags found in yml files in gnuradio 3.8 or 3.8+.

Example: What is the "domain" at the input of a block:

```
inputs:
- label: in
  domain: ?
  dtype: float
  vlen: 1
```
