### ISSUE TITLE
modtool: makeyaml creates incorrect module name

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#3594]
The category generated when calling gr_modtool makeyaml is not correct

```yaml
id: blah_asdf
label: asdf
category: '[{modname.capitalize()}]'
templates:
  imports: import blah
  make: blah.asdf()
inputs:
- label: in
  domain: stream
  dtype: complex
outputs:
- label: out
  domain: stream
  dtype: complex
file_format: 1
```
