### ISSUE TITLE
channels_selective_fading_model.block.yml creates error

### ISSUE THREAD

**Issue by rqlyx** [gnuradio/gnuradio#4787]
@marcusmueller 
The channels_selective_fading_model creates following error:
```
Param - Rician factor (K)(K):
	Value '' not in allowed values
```

 ```
         - id: LOS    
            label: LOS Model
            dtype: enum
            options: ['False', 'True']     
            option_labels: [Rayleigh/NLOS, Rician/LOS]
            option_attributes:    
                hide_K: [all,  '']  // '' should be replaced with 'none' (at least that works for me) --> [all,  none] 
```

[https://github.com/gnuradio/gnuradio/blob/master/gr-channels/grc/channels_selective_fading_model.block.yml](url)

I guess I could change that but i am really not familiar with contributing to public projects and there seem to be a lot of things to be aware of.
