### ISSUE TITLE
SDL Video Sink Chroma Channels Switched

### ISSUE THREAD

**Issue by I-AM-EXFOLIATING** [gnuradio/gnuradio#4991]
`video_sdl::sink_s` and `video_sdl::sink_uc` both appear to use the [YV12 pixel format](https://github.com/gnuradio/gnuradio/blob/master/gr-video-sdl/lib/sink_s_impl.cc#L106) under the hood, which has Y (luma), then V and U (chrominance) planes in order. The code and documentation [assumes the planes are ordered as YUV](https://github.com/gnuradio/gnuradio/blob/master/gr-video-sdl/lib/sink_s_impl.cc#L269) rather than YVU.

This means that in 3-channel YUV 4:4:4 mode (and presumably 2-channel YUV 4:2:2 mode), the Video SDL Sink chrominance channels are switched.

This flowgraph demonstrates that the U and V channels of Video SDL Sink need to be swapped to work correctly.
![image](https://user-images.githubusercontent.com/6624856/128633638-02ae444d-5bde-4f59-a8b9-ddddbe6d1bfd.png)
<details>
<summary>
video_sdl_test.grc
</summary>

```
options:
  parameters:
    author: xfol
    catch_exceptions: 'True'
    category: '[GRC Hier Blocks]'
    cmake_opt: ''
    comment: ''
    copyright: '2021'
    description: ''
    gen_cmake: 'On'
    gen_linking: dynamic
    generate_options: qt_gui
    hier_block_src_path: '.:'
    id: video_sdl_test
    max_nouts: '0'
    output_language: python
    placement: (0,0)
    qt_qss_theme: ''
    realtime_scheduling: ''
    run: 'True'
    run_command: '{python} -u {filename}'
    run_options: prompt
    sizing_mode: fixed
    thread_safe_setters: ''
    title: Video SDL Test
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [8, 8]
    rotation: 0
    state: enabled

blocks:
- name: h
  id: variable
  parameters:
    comment: ''
    value: '300'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [352, 12.0]
    rotation: 0
    state: enabled
- name: samp_rate
  id: variable
  parameters:
    comment: ''
    value: '32000'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [184, 12]
    rotation: 0
    state: enabled
- name: w
  id: variable
  parameters:
    comment: ''
    value: '400'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [272, 12.0]
    rotation: 0
    state: enabled
- name: blocks_float_to_uchar_0
  id: blocks_float_to_uchar
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [592, 160.0]
    rotation: 0
    state: true
- name: blocks_float_to_uchar_0_0
  id: blocks_float_to_uchar
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [592, 224.0]
    rotation: 0
    state: true
- name: blocks_float_to_uchar_0_1
  id: blocks_float_to_uchar
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [592, 192.0]
    rotation: 0
    state: true
- name: blocks_repeat_0
  id: blocks_repeat
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    interp: w * int(h / 3)
    maxoutbuf: '0'
    minoutbuf: '0'
    type: float
    vlen: '3'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [240, 180.0]
    rotation: 0
    state: true
- name: blocks_vector_source_x_0
  id: blocks_vector_source_x
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    repeat: 'True'
    tags: '[]'
    type: float
    vector: '[76.245, 84.47232, 255.0, 149.685, 43.02768, 20.73456, 29.07, 255.0, 106.76544]'
    vlen: '3'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [32, 164.0]
    rotation: 0
    state: true
- name: blocks_vector_to_streams_0
  id: blocks_vector_to_streams
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    num_streams: '3'
    type: float
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [400, 160.0]
    rotation: 0
    state: true
- name: video_sdl_sink_0
  id: video_sdl_sink
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    display_height: h
    display_width: w
    fps: '0'
    height: h
    num_channels: '3'
    type: byte
    width: w
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [784, 156.0]
    rotation: 0
    state: true

connections:
- [blocks_float_to_uchar_0, '0', video_sdl_sink_0, '0']
- [blocks_float_to_uchar_0_0, '0', video_sdl_sink_0, '1']
- [blocks_float_to_uchar_0_1, '0', video_sdl_sink_0, '2']
- [blocks_repeat_0, '0', blocks_vector_to_streams_0, '0']
- [blocks_vector_source_x_0, '0', blocks_repeat_0, '0']
- [blocks_vector_to_streams_0, '0', blocks_float_to_uchar_0, '0']
- [blocks_vector_to_streams_0, '1', blocks_float_to_uchar_0_1, '0']
- [blocks_vector_to_streams_0, '2', blocks_float_to_uchar_0_0, '0']

metadata:
  file_format: 1
```
</details>
