### ISSUE TITLE
In grc yml files, allow specification of parameter vector lengths.

### ISSUE THREAD

**Issue by warnes** [gnuradio/gnuradio#5549]
### Feature Description

Currently, it is necessary to add `asserts` code to ensure that a parameter with a vector type (i.e. `int_vector`) has the correct length.

It would be helpful if the definition of the vector types allowed an optional length specification to be provided, so that input validation can be handled by the gunradio-companion code, rather than using asserts in the yml.

Perhaps this could be accomplished by allowing square brackets enclosing the length to be appended to the vector type specification, for instance: `int_vector[2]`.

For example the current code:
```
- id: dcoff
  category: 'Tuning & Correction'
  label: 'DC Offset Correction [I,Q]'
  dtype: int_vector
  default: [0, 0]
  hide: ${ ('none' if use_iq_dcoff == 'True' else 'part') } 

...

asserts:
- ${ len(dcoff)     == 2 }
```  
could be replaced by simply
```
- id: dcoff
  category: 'Tuning & Correction'
  label: 'DC Offset Correction [I,Q]'
  dtype: int_vector[2]
  default: [0, 0]
  hide: ${ ('none' if use_iq_dcoff == 'True' else 'part') } 
```

### Feature Urgency

medium (would be nice to have in the near future)
