### ISSUE TITLE
Cannot use variable binding in message handlers

### ISSUE THREAD

**Issue by nils-werner** [gnuradio/gnuradio#5781]
### What happened?

I am trying to write a Python block with a variable number of message inputs. Of course I don't want to implement a fixed number of message handlers for a variable number of ports, so I would write one handler and assign all ports to it, with another parameter `port` indicating which port was used:

```python
class example(gr.basic_block):
    def __init__(
        self,
        receivers=1,
    ):
        super().__init__(
            name="Example",
            in_sig=None,
            out_sig=None,
        )

        for i in range(receivers):
            self.message_port_register_in(pmt.intern(f"receiver{i}"))
            self.set_msg_handler(pmt.intern(f"receiver{i}"), functools.partialmethod(self.receiver_handler, port=i))

    def receiver_handler(self, message, port=0):
        print(port, message)
```

and

```yaml
id: message_example
label: Multi Message Example

templates:
  make: >
      example(
        receivers=${receivers},
      )

parameters:
-   id: receivers
    label: Receivers
    dtype: int
    default: '2'
    hide: 'part'

inputs:
-   domain: message
    label: receiver
    optional: true
    multiplicity: ${ receivers }

file_format: 1
```

However this is not possible because internally GNURadio is keeping a string reference to my method, instead of a pointer:

 - [gateway.py](https://github.com/gnuradio/gnuradio/blob/main/gnuradio-runtime/python/gnuradio/gr/gateway.py#L228)
 - [block_gateway_impl.h saving](https://github.com/gnuradio/gnuradio/blob/b2c9623cbd548bd86250759007b80b61bd4a2a06/gnuradio-runtime/lib/block_gateway_impl.h#L41)
 - [block_gateway_impl.h calling](https://github.com/gnuradio/gnuradio/blob/b2c9623cbd548bd86250759007b80b61bd4a2a06/gnuradio-runtime/lib/block_gateway_impl.h#L72)

I believe a more portable solution would be to store method pointers instead of strings here.

### System Information

OS: Arch Linux
GR Installation Method: Conda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Create block from above
2. Connect message inputs to some message source
3. Generate and run graph

### Relevant log output

```
  File "example.py", line 93, in __init__
    self.set_msg_handler(pmt.intern(f"receiver{i}"), functools.partialmethod(self.receiver_handler, i))
  File "/lib/python3.10/site-packages/gnuradio/gr/gateway.py", line 228, in set_msg_handler
    which_port, handler_function.__name__)
AttributeError: 'partialmethod' object has no attribute '__name__'. Did you mean: '__ne__'?
```
