### ISSUE TITLE
Port multiplicity creates inconsistent port names

### ISSUE THREAD

**Issue by nils-werner** [gnuradio/gnuradio#5782]
### What happened?

If you define a block with a variable number of ports, e.g.

```yaml
id: message_example
label: Multi Message Example

templates:
  make: >
      example(
        receivers=${receivers},
      )

parameters:
-   id: receivers
    label: Receivers
    dtype: int
    default: '1'
    hide: 'part'

inputs:
-   domain: message
    label: receiver
    optional: true
    multiplicity: ${ receivers }

file_format: 1
```

GRC will use two different schema for port names:

 - if `receivers == 1` the port name will be `receiver`
 - if `receivers > 1` the port name will be `receiver{n}` where `n` is the port number

This then requires me to do special handling in my implementation code, dealing with both cases in different ways, e.g.

```python
        if self.receivers == 1:
            self.message_port_register_out(pmt.intern("data"))
            self.message_port_register_in(pmt.intern("receiver"))
            self.set_msg_handler(pmt.intern("receiver"), self.receiver_handler)
        else:
            for i in range(receivers):
                self.message_port_register_out(pmt.intern(f"data{i}"))
                self.message_port_register_in(pmt.intern(f"receiver{i}"))
                self.set_msg_handler(pmt.intern(f"receiver{i}"), self.receiver_handler)
```

It would be more consistent and handy if GRC simply always used `receiver{n}`, no matter what the value of `receivers`

### System Information

OS: Arch Linux
GR Installation Method: Conda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Create a block like above
2. Create signal flow graph
3. Inspect the created flowgraph and discover the different handling of port names
