### ISSUE TITLE
Cannot create hier block with variable vector length

### ISSUE THREAD

**Issue by nils-werner** [gnuradio/gnuradio#6045]
### What happened?

When trying to create a hier block with a variable vector length parameter, the resulting YAML file has a static `vlen` field in its inputs and outputs.

The problem seems to be that [`port.vlen` in the generator](https://github.com/gnuradio/gnuradio/blob/main/grc/core/generator/hier_block.py#L102)

```python
p['vlen'] = var_or_value(port.vlen)
```

has the value `1` and not the name of the parameter `vlen` that I'm using. `var_or_value()` then has no effect.

### System Information

OS: Arch Linux
GR Installation Method: Conda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.3.0

### Steps to Reproduce the Problem

Create this flowgraph

```yaml
options:
  parameters:
    author: ''
    catch_exceptions: 'True'
    category: '[GRC Hier Blocks]'
    cmake_opt: ''
    comment: ''
    copyright: ''
    description: ''
    gen_cmake: 'On'
    gen_linking: dynamic
    generate_options: hb
    hier_block_src_path: '.:'
    id: test
    max_nouts: '0'
    output_language: python
    placement: (0,0)
    qt_qss_theme: ''
    realtime_scheduling: ''
    run: 'True'
    run_command: '{python} -u {filename}'
    run_options: prompt
    sizing_mode: fixed
    thread_safe_setters: ''
    title: Not titled yet
    window_size: (1000,1000)
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [8, 8]
    rotation: 0
    state: enabled

blocks:
- name: pad_sink_0
  id: pad_sink
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    label: out
    num_streams: '1'
    optional: 'False'
    type: complex
    vlen: vlen
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [200, 124.0]
    rotation: 0
    state: true
- name: pad_source_0
  id: pad_source
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    label: in
    maxoutbuf: '0'
    minoutbuf: '0'
    num_streams: '1'
    optional: 'False'
    type: complex
    vlen: vlen
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [40, 124.0]
    rotation: 0
    state: true
- name: vlen
  id: parameter
  parameters:
    alias: ''
    comment: ''
    hide: none
    label: Vlen
    short_id: ''
    type: intx
    value: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [184, 8.0]
    rotation: 0
    state: true

connections:
- [pad_source_0, '0', pad_sink_0, '0']

metadata:
  file_format: 1
  grc_version: 3.10.3.0
```

and generate the YAML and Python block files. The output will be `vlen: 1` instead of `vlen: ${ vlen }`
