### ISSUE TITLE
4.0: expressing signal measurement errors/confidence intervals

### ISSUE THREAD

**Issue by RalphSteinhagen** [gnuradio/gnuradio#6182]
### Feature Description

We would love to get some feedback and comments on the following feature proposal:

One 'quirky feature' that we implemented in our OOT modules at FAIR is the computation of [confidence intervals](https://en.wikipedia.org/wiki/Confidence_and_prediction_bands) alongside the signal value. Depending on the use case, the confidence interval accounts for the signal's [measurement error](https://en.wikipedia.org/wiki/Errors_and_residuals) or [measurement uncertainty](https://en.wikipedia.org/wiki/Measurement_uncertainty) (e.g. r.m.s. or it's true standard deviation) which are graphically represented typically by either [error bars](https://en.wikipedia.org/wiki/Error_bar) or error bands.

Presently, our working solution is to use two floating-point inputs/outputs for our blocks which becomes somewhat convoluted for large flow graphs and doesn't extend well for the wealth of existing GR blocks.

I was wondering whether this could be rationalised and maybe expressed more efficiently and safely, for example, through a new dedicated type carrying the signal value and its error/confidence interval.

### Feature Urgency

medium (would be nice to have in the near future)

### More Information

Academic/scientific rigor and graphical representation aside, this confidence interval is also a key ingredient for (fail-)safe automation and critical systems, e.g. through 
  * enabling adaptive gain-scheduling in feedback loops, or
  * specific actions based on the actual S/N thresholds (e.g. stopping a control loop, robust signal-level interlocks, ...), or 
  * compositing or choosing a suitable fall-back signal from a set of redundant measurements based on their effective S/N ratio.

<br/>
Paraphrasing @mormj's et al. ideas on the GR Architecture channel, the primary options appear to be:
  1. through a new non-primitive but nevertheless numerically efficient type-safe data type,
  1. via any custom type to be used as a port type and having one specialisation for the '(value, error)' tuple, or
  1. ... *your input here*.

Of course, all done in a type-safe way and with fall-back options for blocks unaware of this type (e.g. similarly to how it's being done for the propagation of tags right now).

<br/>
Some additional questions on the use case's applicability:

  * How are other fields with mission-critical systems handling this issue?
  * Are there others interested in this feature?
  * Are there other related features/constraints that would be useful/pertinent regarding the above?

Any information from other industries/fields would be much appreciated! Looking forward to your comments!

**Comment by mormj** [comment]
To summarize the conversation in the Architecture Group meeting, we think the following can be addressed by extending the "bus port" concept of GRC into the runtime:
- Create port groups that represent some tuple of ports
- This prevents the interleaving of signal/error values
- Available from the C++/python api

Example:
```yaml
ports:
  - id: in_sig
    label: Input Signal Value
    dtype: rf32
    direction: input
  - id: in_err
    label: Input Signal Error
    dtype: rf32
    direction: input
  - id: out_sig
    label: Output Signal Value
    dtype: rf32
    direction: output
  - id: out_err
    label: Output Signal Error
    dtype: rf32
    direction: output
  - id: in
    dtype: bundle [or tuple]
    ports: [in_sig, in_err]
  - id: out
    dtype: bundle [or tuple]
    ports: [out_sig, out_err]
```
Then the bundled ports could be used to connect (assuming tuple types are matching)

```python
tb.connect(x, "out", y, "in")
