### ISSUE TITLE
Block properties: allow variable expressions for enum fields

### ISSUE THREAD

**Issue by eltos** [gnuradio/gnuradio#6870]
### Feature Description

Block properties with `dtype: enum` are the only properties which can not be controlled dynamically by variables or expressions.
The drop-down menu for enums simply does not allow entering variables names.

Take the [File source](https://github.com/gnuradio/gnuradio/blob/8a55c4f14d7cd06f21e162e586130ce0756f9d89/gr-blocks/grc/blocks_file_source.block.yml#L17-L22) as an example:
Here "Repeat" is even runtime-adjustable, but because it is not possible to assign it via a variable, there is no way to actually change it at runtime.
```yml
-   id: repeat
    label: Repeat
    dtype: enum
    default: 'True'
    options: ['True', 'False']
    option_labels: ['Yes', 'No']
```
![grafik](https://github.com/gnuradio/gnuradio/assets/19860638/f0c2d546-3ffe-4635-92bc-2b4f5b8dc680)

It would be good to have the ability to enter expressions, similar to how it is done for other types which have `option_labels` defined, for example [File sink](https://github.com/gnuradio/gnuradio/blob/8a55c4f14d7cd06f21e162e586130ce0756f9d89/gr-blocks/grc/blocks_file_sink.block.yml#L22C1-L27C33):
```yml
-   id: unbuffered
    label: Unbuffered
    dtype: bool
    default: 'False'
    options: ['False', 'True']
    option_labels: ['Off', 'On']
```
![grafik](https://github.com/gnuradio/gnuradio/assets/19860638/665a0711-97b7-4804-b327-94167bbae603)

In this very specific example, one could also change enum to bool, but this feature request is about a general way to solve this constraint.

As a nice side effect, this would also allow creating type-dynamic hier blocks by controlling the blocks "Type" parameter (which is an enum) via a common variable that could be exposed as a (non-runtime adjustable) hier-block parameter.

### Feature Urgency

high (impacts broad portion of ecosystem)

### More Information

/label GRC

**Comment by martinling** [comment]
Here's a real-world use case where the lack of this feature is extremely painful.

I've just published a [DVB-S2 receiver test](https://github.com/martinling/dvbs2-rx-testbench) flowgraph which outputs three adjacent signals.

Generating a DVB-S2 signal requires a series of 7 different specialised blocks, but because of the way the protocol works, all of these blocks needs to know the main modulation and coding parameters. And they're all configured as enums. So if, for instance you want to change the code rate from 1/2 to 1/4 in this flowgraph, you need to change it by hand on 21 different blocks:

![dvbs2_rx_test](https://github.com/gnuradio/gnuradio/assets/673823/f5dcc11a-38fe-4c5b-9cc3-d75ff4b7b7d3)

**Comment by AsriFox** [comment]
I agree! I have encountered the DVB-S2 enum problem as well.
Fortunately, in GRC all values are basically strings interpreted by Python / Mako templates. It means we can do workarounds in block definitions (.block.yml) like this:
```yaml
parameters:
- id: constellation
  label: Signal Constellation
  dtype: string
  default: MOD_QPSK
  options: [ MOD_QPSK, MOD_8PSK ]
  option_labels: [ 'QPSK', '8PSK' ]

templates:
  imports: from gnuradio import dtv
  make: dtv.dvbs2_modulator_bc(dtv.FECFRAME_NORMAL, dtv.${rate}, dtv.${constellation}, dtv.INTERPOLATION_OFF)
```
Because `dtype` is `string`, you can input variable names and even python expressions in this field. This also works when `dtype` is set to `int` or `bool`.
Unfortunately, there are no checks against `options` when interpreting values - they just get passed into templates as strings.
