### ISSUE TITLE
Low Pass Filter broken unable to get valid Window config.

### ISSUE THREAD

**Issue by Renlor** [gnuradio/gnuradio#7476]
### What happened?

The Low Pass Filters generates a `Param` error on the `Window` config regardless of which window type is selected.
```
Param - Window(win):
	Value "window.WIN_HAMMING" cannot be evaluated:
	name 'window' is not defined
```
This appears to be related to #6526 which notes that #6523 was the breaking change, as far as I can tell this change had nothing to do with the error although the change was reverted in #6527 seemingly as a result of the complaint about LPF not working.

### System Information

OS: Mac 14.5 arm64
GR Installation Method: Anaconda
Using an RTLSDR, but not necessary to reproduce the problem.

### GNU Radio Version

4.0-git (dev-4.0)

### Specific Version

3.10.5.1, 3.10.11.0

### Steps to Reproduce the Problem

1. Ensure anaconda is installed and up to date
2. Create environment.yml file in an empty directory (e.g. radio-test).
```yaml
---
name: radio-test
dependencies:
- conda-forge::gnuradio-core=3.10.5.1
- conda-forge::gnuradio-grc
- conda-forge::gnuradio-iio
- conda-forge::gnuradio-qtgui
- conda-forge::gnuradio-soapy
- conda-forge::gnuradio-uhd
- conda-forge::gnuradio-video-sdl
- conda-forge::gnuradio-zeromq
- conda-forge::rtl-sdr
- conda-forge::gnuradio-osmosdr
```
3. setup the environment and start gnuradio
```sh
cd radio-test
conda env create
conda env activate radio-test
gnuradio-companion

4. Add a `Low Pass Filter` or `FFT Low Pass Filter` to the graph
5. Open the `Low Pass Filter` config, on the `General` tab note that the errors on the `Low Pass Filter` always contain a `Param` error as follows regardless of which `Window` is selected.
```
Param - Window(win):
	Value "window.WIN_BLACKMAN" cannot be evaluated:
	name 'window' is not defined
```

### Relevant log output

```shell
Param - Window(win):
	Value "window.WIN_BLACKMAN" cannot be evaluated:
	name 'window' is not defined
```
